# Generated by Django 2.1.2 on 2018-10-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=120)),
                ('done', models.BooleanField(default=False)),
                ('duedate', models.DateField()),
            ],
        ),
    ]
